@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiam9objQuQGdtYWlsLmNvbSIsIm5hbWUiOiJKb2huIiwiaWF0IjoxNzU5OTU0NzM2LCJleHAiOjE3NTk5ODM1MzZ9.fwJnbHdfXB1Xh0FAsg1Eh3ZlGZshWL6pz9saTT2Fo9o

### Criar abrigo
POST http://localhost:4000/shelters
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Alegria",
  "cnpj": "12.366.678/0001-90",
  "endereco": "Episcopal, 458",
  "telefone": "(11) 4433-4444",
  "responsavel": "",
  "urlImage": "https://exemplo.com/abrigo.jpg",
  "isActive": false
}

### Listar todos os abrigos
GET http://localhost:4000/shelters

### Buscar abrigo por nome
GET http://localhost:4000/shelters?nome=Amigos

### Buscar abrigos ativos
GET http://localhost:4000/shelters?isActive=true

### Buscar abrigo por ID
GET http://localhost:4000/shelters/1
Content-Type: application/json
Authorization: Bearer {{token}}


### Atualizar abrigo
PUT http://localhost:4000/shelters/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "telefone": "(11) 3333-5555",
  "responsavel": "Zé"
}

### Deletar abrigo
DELETE http://localhost:3000/shelters/2
DELETE http://localhost:4000/shelters/1

